'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ShippingLocationControl
    
    '''<summary>
    '''Hidden_POSLatitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Hidden_POSLatitude As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HIdden_POSLongtitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HIdden_POSLongtitude As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''ShippingStatusLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShippingStatusLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ShippingPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShippingPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''EventTypeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EventTypeName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''POSItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents POSItems As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''getKitItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents getKitItems As Global.System.Web.UI.WebControls.LinqDataSource
    
    '''<summary>
    '''ShippingAddressLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShippingAddressLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''AttLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AttLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ShippedViaLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShippedViaLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ShippedTypeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShippedTypeLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TrackingLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrackingLabel As Global.System.Web.UI.WebControls.Label
End Class
