'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Shipping
    
    '''<summary>
    '''BreadCrumbPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BreadCrumbPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ReturnLink1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReturnLink1 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''selectedDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selectedDateLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DateRangeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DateRangeLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''FromDatePicker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FromDatePicker As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''ToDatePicker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToDatePicker As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''btnChangeDateRange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnChangeDateRange As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ShippingCostsGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShippingCostsGrid As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''GetShippingCosts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GetShippingCosts As Global.System.Web.UI.WebControls.SqlDataSource
End Class
