'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class OffPremiseDashboard
    
    '''<summary>
    '''hiddenUserID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenUserID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hiddenClientID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenClientID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''SideMenuControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SideMenuControl As Global.EventManagerApplication.SideMenuControl
    
    '''<summary>
    '''SelectedSupplierLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectedSupplierLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DateRangeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DateRangeLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''SelectedSupplier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectedSupplier As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''GetSupplierList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GetSupplierList As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''FromDatePicker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FromDatePicker As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''ToDatePicker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToDatePicker As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''btnChangeDateRange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnChangeDateRange As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnViewWeek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnViewWeek As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnViewMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnViewMonth As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''MainPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''DefaultMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DefaultMessage As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''NoResultLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoResultLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ReportPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReportPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''VolumeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VolumeLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''EventVolumeChart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EventVolumeChart As Global.Telerik.Web.UI.RadHtmlChart
    
    '''<summary>
    '''getEventCounts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents getEventCounts As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''SampledTotalLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SampledTotalLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RadHtmlChart1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadHtmlChart1 As Global.Telerik.Web.UI.RadHtmlChart
    
    '''<summary>
    '''getSampledWeeklyTotals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents getSampledWeeklyTotals As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''BottlesSoldTotalLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BottlesSoldTotalLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RadHtmlChart2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadHtmlChart2 As Global.Telerik.Web.UI.RadHtmlChart
    
    '''<summary>
    '''getSoldWeeklyTotals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents getSoldWeeklyTotals As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''ConversionRateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConversionRateLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RadHtmlChart3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadHtmlChart3 As Global.Telerik.Web.UI.RadHtmlChart
    
    '''<summary>
    '''GetConversionRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GetConversionRate As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''CaseDisplayLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseDisplayLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RadHtmlChart5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadHtmlChart5 As Global.Telerik.Web.UI.RadHtmlChart
    
    '''<summary>
    '''SqlDataSource1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource1 As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''AverageCasesLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AverageCasesLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RadHtmlChart6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadHtmlChart6 As Global.Telerik.Web.UI.RadHtmlChart
    
    '''<summary>
    '''SqlDataSource2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource2 As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''RevenueLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RevenueLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RadHtmlChart4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadHtmlChart4 As Global.Telerik.Web.UI.RadHtmlChart
    
    '''<summary>
    '''GetEstimatedRevenue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GetEstimatedRevenue As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''BrandsPromotedChart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BrandsPromotedChart As Global.Telerik.Web.UI.RadHtmlChart
    
    '''<summary>
    '''BrandTotalList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BrandTotalList As Global.Telerik.Web.UI.RadListView
    
    '''<summary>
    '''GetBrandTotalSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GetBrandTotalSummary As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''getBrandTotals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents getBrandTotals As Global.System.Web.UI.WebControls.SqlDataSource
End Class
