'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CityWeatherControl

    '''<summary>
    '''lblDay0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDay0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMonth0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMonth0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTempMin0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTempMin0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTempMax0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTempMax0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgWeatherIcon0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgWeatherIcon0 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblMain0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMain0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDay1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDay1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMonth1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMonth1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTempMin1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTempMin1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTempMax1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTempMax1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgWeatherIcon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgWeatherIcon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblMain1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMain1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDay2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDay2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMonth2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMonth2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDayName2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDayName2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTempMin2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTempMin2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTempMax2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTempMax2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgWeatherIcon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgWeatherIcon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblMain2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMain2 As Global.System.Web.UI.WebControls.Label
End Class
