'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EventDetails_Ambassador
    
    '''<summary>
    '''RadAjaxManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager
    
    '''<summary>
    '''RadAjaxLoadingPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxLoadingPanel1 As Global.Telerik.Web.UI.RadAjaxLoadingPanel
    
    '''<summary>
    '''RadPersistenceManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPersistenceManager1 As Global.Telerik.Web.UI.RadPersistenceManager
    
    '''<summary>
    '''LatitudeTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LatitudeTextBox As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''LongtitudeTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LongtitudeTextBox As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''LocationTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LocationTextBox As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''LocationNameMap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LocationNameMap As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lblStreetAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStreetAddress As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCityAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCityAddress As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''msgLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msgLabel As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''BreadCrumbPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BreadCrumbPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ReturnLink1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReturnLink1 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''EventNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EventNameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''EventDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EventDateLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''EventIDLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EventIDLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''informationTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents informationTab As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''StatusPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''btnUpdateStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateStatus As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DetailsPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DetailsPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''StatusLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''EventTypeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EventTypeLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''MarketLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MarketLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''SupplierLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SupplierLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DateLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''StartTimeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StartTimeLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''EndTimeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EndTimeLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''HoursLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HoursLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BrandsLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BrandsLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''AttireLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AttireLabel As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''POSLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents POSLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''SamplingLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SamplingLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''AdditionalInstruvtionsLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AdditionalInstruvtionsLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DescriptionLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DescriptionLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''AccountHyperLink1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AccountHyperLink1 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''AccountNameLabel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AccountNameLabel1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''AccountAddressLabel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AccountAddressLabel1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DirectionsPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DirectionsPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''SelectedAmbassadorPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectedAmbassadorPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''SelectedDirectionsName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectedDirectionsName As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''getAmbassadorList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents getAmbassadorList As Global.System.Web.UI.WebControls.LinqDataSource
    
    '''<summary>
    '''EnterAddressPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EnterAddressPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtFromAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFromAddress As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CityLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CityLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''WeatherForcastPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WeatherForcastPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''WeatherListRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WeatherListRepeater As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''getWeatherList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents getWeatherList As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''staffingPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents staffingPanel As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''StaffingPnel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StaffingPnel1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''RadTabStrip1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTabStrip1 As Global.Telerik.Web.UI.RadTabStrip
    
    '''<summary>
    '''statusTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents statusTab As Global.Telerik.Web.UI.RadTab
    
    '''<summary>
    '''RadMultiPage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadMultiPage1 As Global.Telerik.Web.UI.RadMultiPage
    
    '''<summary>
    '''RadPageView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView1 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''positionsStaffedCountLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents positionsStaffedCountLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''positionsAvailableCountLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents positionsAvailableCountLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''StaffingList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StaffingList As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''GetEventStaff2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GetEventStaff2 As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''ProductTrainingPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProductTrainingPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''TrainingRadTabStrip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrainingRadTabStrip As Global.Telerik.Web.UI.RadTabStrip
    
    '''<summary>
    '''coursesTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents coursesTab As Global.Telerik.Web.UI.RadTab
    
    '''<summary>
    '''scoresTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents scoresTab As Global.Telerik.Web.UI.RadTab
    
    '''<summary>
    '''documentsTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents documentsTab As Global.Telerik.Web.UI.RadTab
    
    '''<summary>
    '''TrainingRadMultiPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrainingRadMultiPage As Global.Telerik.Web.UI.RadMultiPage
    
    '''<summary>
    '''RadPageView5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView5 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''EventCourseListView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EventCourseListView As Global.Telerik.Web.UI.RadListView
    
    '''<summary>
    '''getEventCourse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents getEventCourse As Global.System.Web.UI.WebControls.LinqDataSource
    
    '''<summary>
    '''InvitationButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InvitationButton As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''msgTrainingLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msgTrainingLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''InvitationPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InvitationPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''InvitationEmailTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InvitationEmailTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnSubmitInvitation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitInvitation As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnCancelInvitation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelInvitation As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''getBrandTrainingList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents getBrandTrainingList As Global.System.Web.UI.WebControls.LinqDataSource
    
    '''<summary>
    '''HiddenBrandID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenBrandID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''RadPageView6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView6 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''TestScoresPlaceHolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TestScoresPlaceHolder As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''RadPageView7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView7 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''DocumentsPlaceHolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DocumentsPlaceHolder As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''LogisticsPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LogisticsPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''POSRadTabStrip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents POSRadTabStrip As Global.Telerik.Web.UI.RadTabStrip
    
    '''<summary>
    '''kitsTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents kitsTab As Global.Telerik.Web.UI.RadTab
    
    '''<summary>
    '''shippinglocationTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents shippinglocationTab As Global.Telerik.Web.UI.RadTab
    
    '''<summary>
    '''costTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents costTab As Global.Telerik.Web.UI.RadTab
    
    '''<summary>
    '''POSRadMultiPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents POSRadMultiPage As Global.Telerik.Web.UI.RadMultiPage
    
    '''<summary>
    '''RadPageView8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView8 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''noPosItemsPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents noPosItemsPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''noPosItemsLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents noPosItemsLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''POSKitRequestedLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents POSKitRequestedLabel As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''POSPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents POSPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''EventTypeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EventTypeName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''POSItemList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents POSItemList As Global.Telerik.Web.UI.RadListBox
    
    '''<summary>
    '''errorLabel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errorLabel2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''labelForKits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labelForKits As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''KitRequested control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents KitRequested As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''SendToList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SendToList As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''NotesTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NotesTextBox As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''btnSavePosKitRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSavePosKitRequest As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''SuccessLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SuccessLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RadPageView9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView9 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''Hidden_POSLatitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Hidden_POSLatitude As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HIdden_POSLongtitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HIdden_POSLongtitude As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''ShippingStatusLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShippingStatusLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ShippingPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShippingPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ShippingEventTypeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShippingEventTypeName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''POSItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents POSItems As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''getKitItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents getKitItems As Global.System.Web.UI.WebControls.LinqDataSource
    
    '''<summary>
    '''ShippingAddressLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShippingAddressLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''AttLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AttLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ShippedViaLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShippedViaLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ShippedTypeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShippedTypeLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TrackingLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrackingLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RadPageView10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView10 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''CostShippingStatusLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CostShippingStatusLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CostPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CostPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''POSItemsRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents POSItemsRepeater As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''getKitItems2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents getKitItems2 As Global.System.Web.UI.WebControls.LinqDataSource
    
    '''<summary>
    '''ShippingLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShippingLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ShippingRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShippingRepeater As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''getShippingCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents getShippingCost As Global.System.Web.UI.WebControls.LinqDataSource
    
    '''<summary>
    '''LogisticsLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LogisticsLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LogisticsRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LogisticsRepeater As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''TotalCostLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TotalCostLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RecapPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecapPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''RecapStausLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecapStausLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PhotoCountLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PhotoCountLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PrintPDFLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PrintPDFLink As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnCreatePDF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreatePDF As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''msgLabel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msgLabel2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''QuestionaireControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuestionaireControl As Global.EventManagerApplication.QuestionaireControl
    
    '''<summary>
    '''GalleryPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GalleryPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''btnAddPhotos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddPhotos As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''PhotoListView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PhotoListView As Global.Telerik.Web.UI.RadListView
    
    '''<summary>
    '''errorLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errorLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''getImageList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents getImageList As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''UploadPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UploadPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''PhotoAsyncUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PhotoAsyncUpload As Global.Telerik.Web.UI.RadAsyncUpload
    
    '''<summary>
    '''btnUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpload As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelUpload As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RadWindowManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowManager1 As Global.Telerik.Web.UI.RadWindowManager
    
    '''<summary>
    '''Details control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Details As Global.Telerik.Web.UI.RadWindow
    
    '''<summary>
    '''RadNotification1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadNotification1 As Global.Telerik.Web.UI.RadNotification
    
    '''<summary>
    '''RadNotification2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadNotification2 As Global.Telerik.Web.UI.RadNotification
    
    '''<summary>
    '''RadScriptBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptBlock1 As Global.Telerik.Web.UI.RadScriptBlock
End Class
