'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Dashboard5

    '''<summary>
    '''row1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents row1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ClientNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClientNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnConfiguration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfiguration As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnViewStaffConfiguration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnViewStaffConfiguration As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEmail As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUsers As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnViewSiteConfiguration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnViewSiteConfiguration As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnWeatherAPI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnWeatherAPI As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''StatsPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatsPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''CurrentLoginCountLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CurrentLoginCountLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CurrentLoginIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CurrentLoginIcon As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''TotalLoginCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TotalLoginCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TotalLoginIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TotalLoginIcon As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''NewVisitPercentLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewVisitPercentLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''NewVisitPercentIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewVisitPercentIcon As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''RecapsSubmittedLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecapsSubmittedLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RecapsSubmittedIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecapsSubmittedIcon As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ApprovedEventsCountLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ApprovedEventsCountLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ApprovedEventIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ApprovedEventIcon As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''NewEventsCountLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewEventsCountLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''NewEventIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewEventIcon As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''NewRegistrationsLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewRegistrationsLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''NewRegistrationsIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewRegistrationsIcon As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''NewAssignmentsLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewAssignmentsLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''NewAssignmentsIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewAssignmentsIcon As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''NewAmbassadorsLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewAmbassadorsLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''NewAmbassadorsIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewAmbassadorsIcon As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lblASPVersion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblASPVersion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PanelSiteConfiguration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelSiteConfiguration As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''PanelStaffConfiguration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelStaffConfiguration As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ButtonStaffConfiguration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonStaffConfiguration As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''PanelWeatherAPI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelWeatherAPI As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ButtonWeatherAPIConfiguration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonWeatherAPIConfiguration As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSaveWeather control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveWeather As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnUpdateWeather control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateWeather As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpdateWeatherResultLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateWeatherResultLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAppID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAppID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBoxAppID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxAppID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblURL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblURL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''URLTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents URLTextBox As Global.System.Web.UI.WebControls.TextBox
End Class
