'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EditField
    
    '''<summary>
    '''RadAjaxPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanel1 As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''msgLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msgLabel As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''ActivityTypeNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ActivityTypeNameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdate As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''ColumnNameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ColumnNameTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RequiredFieldTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldTextBox As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''columnTypeList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents columnTypeList As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''DescriptionPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DescriptionPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescription As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''MultilinePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MultilinePanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtLines control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLines As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ChoicePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChoicePanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtChioces control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChioces As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DisplayOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DisplayOptions As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''YesNoPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents YesNoPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ckbYesNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckbYesNo As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''NumberPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NumberPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtDecimalPlace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDecimalPlace As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtDefaultNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDefaultNumber As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ckbPercentage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckbPercentage As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''DatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DatePanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ckbDateFormat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckbDateFormat As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''ckbDateDisplayFormat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckbDateDisplayFormat As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''ckbDateDefualtValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckbDateDefualtValue As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''TimePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TimePanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ckbTimeFormat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckbTimeFormat As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''CurrencyPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CurrencyPanel As Global.System.Web.UI.WebControls.Panel
End Class
